export const TIMER_ACTIONS = {
  IDLE: 'IDLE',
  START: 'START',
  PAUSE: 'PAUSE',
  RESET: 'RESET',
  RESTART: 'RESTART',
  TICK: 'TICK',
  CHANGE_SESSION: 'CHANGE_SESSION',
  ADD_MINUTES: 'ADD_MINUTES',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  COUNT_SESSIONS: 'COUNT_SESSIONS',
  RESET_COUNT_WORK_SESSIONS: 'RESET_COUNT_WORK_SESSIONS',
  RESET_ALL_COUNT_SESSIONS: 'RESET_ALL_COUNT_SESSIONS',
  STOP_ALARM: 'STOP_ALARM',
  SESSION_COMPLETE: 'SESSION_COMPLETE'
};